Simplify conditions with the same result and avoid extra validations.
apache/maven-resolver pull request #119
Opened 2021-09-02 18:40 UTC by arturobernalg

2021-09-04 19:10 UTC, michael-o requested changes

2021-09-04 19:10 UTC, michael-o commented on maven-resolver-api/src/main/java/org/eclipse/aether/resolution/ArtifactResolutionException.java
> +        this.results = results;
This actually changes semantics b/c if `results` is null the instance private field wll never be null. WDYT?

2021-09-04 19:10 UTC, michael-o commented on maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/ChecksumCalculator.java
> +                    throw new IOException( targetFile + " contains only " + total
Can you explain this change?

2021-09-04 19:10 UTC, michael-o commented on maven-resolver-transport-wagon/src/main/java/org/eclipse/aether/transport/wagon/WagonTransporter.java
> +        if ( wagonHint.length() <= 0 )
Why not `isEmpty()`?

2021-09-04 19:10 UTC, michael-o commented on maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/ClassicDependencyManager.java
> +                management = new DependencyManagement();
This is because `management` is always null here?

2021-09-05 06:29 UTC, arturobernalg commented on maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/ChecksumCalculator.java
> +                    throw new IOException( targetFile + " contains only " + total
`total < dataOffset` is always true, otherwise the conditions of the loop would be true and would be exit.

2021-09-05 06:30 UTC, arturobernalg commented on maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/ClassicDependencyManager.java
> +                management = new DependencyManagement();
Correct. `management ` in this point is always `null`. No need extra validations.

2021-09-05 06:51 UTC, arturobernalg commented on maven-resolver-api/src/main/java/org/eclipse/aether/resolution/ArtifactResolutionException.java
> +        this.results = results;
Hi @michael-o
The semantics has changed, What change do you propose?

2021-09-05 10:44 UTC, michael-o commented on maven-resolver-api/src/main/java/org/eclipse/aether/resolution/ArtifactResolutionException.java
> +        this.results = results;
Leave it as-is. I don't have a better idea here since we don't know whether the passed results can be null.

2021-09-05 10:45 UTC, michael-o commented on maven-resolver-api/src/main/java/org/eclipse/aether/resolution/ArtifactResolutionException.java
> +        this.results = results;
Same here.

2021-09-05 11:48 UTC, arturobernalg commented on maven-resolver-api/src/main/java/org/eclipse/aether/resolution/ArtifactResolutionException.java
> +        this.results = results;
Done.

2021-09-05 12:31 UTC, arturobernalg commented on maven-resolver-transport-wagon/src/main/java/org/eclipse/aether/transport/wagon/WagonTransporter.java
> +        if ( wagonHint.length() <= 0 )
https://github.com/apache/maven-resolver/pull/123

2021-09-05 18:30 UTC, michael-o commented on maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/ChecksumCalculator.java
> +                    throw new IOException( targetFile + " contains only " + total
But why is the break gone?

2021-09-07 04:58 UTC, arturobernalg commented on maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/ChecksumCalculator.java
> +                    throw new IOException( targetFile + " contains only " + total
Hi,
Now its not need it. when ` read < 0`  always throw an Exceptions and the process will be interrupted

2021-09-08 07:56 UTC, michael-o commented on maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/ChecksumCalculator.java
> +                    throw new IOException( targetFile + " contains only " + total
Yes, makes sense.

2021-09-08 11:00 UTC, closed without merging

2025-06-13 08:26 UTC, jira-importer commented
Resolve #1396

2025-06-13 08:37 UTC, jira-importer commented
Resolve #1396