Refactor selector
apache/maven-resolver pull request #138
Opened 2021-12-12 21:45 UTC by cstamas

To make it more extensible

2021-12-12 21:49 UTC, michael-o commented
Need to take a look at this with a sober mind.

2021-12-12 21:52 UTC, michael-o commented
Maybe this will be simpler when service locator will be gone?

2021-12-12 21:56 UTC, cstamas commented
> Maybe this will be simpler when service locator will be gone?

Def, so can't wait to drop SL

2021-12-12 21:57 UTC, michael-o commented
> > Maybe this will be simpler when service locator will be gone?
> 
> Def, so can't wait to drop SL

Does this make sense while SL is still there?

2021-12-13 08:36 UTC, pzygielo commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactorySelectorSupport.java
> +     * to {@link LocalReadWriteLockNamedLockFactory#NAME}.
Here the default actually used is out of control of this class, so this comment does not seem right.

2021-12-13 08:38 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactorySelectorSupport.java
> +     * to {@link LocalReadWriteLockNamedLockFactory#NAME}.
Fixed, thanks!

2021-12-17 16:48 UTC, cstamas commented
> Does this make sense while SL is still there?

IMHO yes

2021-12-18 23:03 UTC, michael-o requested changes
I think this deserves a JIRA issue with a description who would benefit from. The change itself is fine by me.

2021-12-18 23:07 UTC, merged

2025-06-13 08:06 UTC, jira-importer commented
Resolve #944

2025-06-13 08:06 UTC, jira-importer commented
Resolve #944