[MRESOLVER-231] Make extension point where checksums are injected.
apache/maven-resolver pull request #141
Opened 2021-12-16 16:49 UTC by cstamas

This feature allows Resolver to get "expected" checksums ahead
of remote transport (resolution), hence, it may operate with
"good known" checksums for example (or use any other source).

2022-01-29 10:31 UTC, michael-o requested changes

2022-01-29 10:31 UTC, michael-o commented on maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/checksum/ChecksumPolicy.java
> +        REMOTE, SMART, PROVIDED
I absolutely dislike the term "smart" because computers aren't smart. They are stupid. The inline checksums are also remote. I would prefer some other term for it.

2022-01-29 10:31 UTC, michael-o commented on maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/ChecksumValidator.java
> +               && validateChecksums( actualChecksums, ChecksumKind.SMART, inlinedChecksums ) )
`SMART` => `REMOTE_INLINE`?

2022-01-29 10:31 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumSource.java
> +                    LOGGER.warn( "Could not read provided checksum for {} at path {}", metadata, checksumPath, e );
Add single quotes to args.

2022-01-29 10:31 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumSource.java
> +                            LOGGER.debug( "{} -> {}:{}", ArtifactIdUtils.toId( artifact ),
Why does this one use `toId()` and the other one not?

2022-01-29 10:31 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumSource.java
> +    public Map<String, String> getProvidedMetadataChecksums( RepositorySystemSession session,
Both methods look almost identical, would it make sense to refactor the common code to a private method?

2022-01-29 10:31 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumSource.java
> +                    LOGGER.warn( "Could not read provided checksum for {} at path {}",
Same here

2022-01-29 15:26 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/AbstractChecksumPolicy.java
> +        if ( ChecksumKind.REMOTE == kind )
`( kind & KIND_UNOFFICIAL ) == 0` is official, no (result is zero). "Official" now is explicit.

2022-01-29 15:26 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java
> +    Map<String, ProvidedChecksumsSource> provideDownloadChecksumSources(
fixed

2022-01-29 15:35 UTC, cstamas commented on maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/checksum/ChecksumPolicy.java
> +        REMOTE, SMART, PROVIDED
fixed

2022-01-29 15:36 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumSource.java
> +                            LOGGER.debug( "{} -> {}:{}", ArtifactIdUtils.toId( artifact ),
There is no `ArtifactUtils.toId( Metadata.class )`...

2022-01-29 15:43 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumSource.java
> +    public Map<String, String> getProvidedMetadataChecksums( RepositorySystemSession session,
Collapsed into private method

2022-01-29 18:12 UTC, michael-o commented
can you really make always the assumption that provided is always local?

2022-01-29 18:55 UTC, cstamas commented
> can you really make always the assumption that provided is always local?

You are right here, so you propose to make it simply `PROVIDED` (remove the `LOCAL_` prefix)?

2022-01-29 19:15 UTC, michael-o commented
> > can you really make always the assumption that provided is always local?
> 
> You are right here, so you propose to make it simply `PROVIDED` (remove the `LOCAL_` prefix)?

Yes, what provided means is upto the implementor.

2022-01-29 19:16 UTC, michael-o commented
Crunching on inline and external.

2022-01-29 22:00 UTC, cstamas commented
@michael-o while crunching, refactored and made it simpler, last two commits...

2022-01-29 22:14 UTC, cstamas commented
Meh, it's again site/javadoc that fails.... 😞

2022-01-30 15:37 UTC, michael-o requested changes

2022-01-30 15:37 UTC, michael-o commented on maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnectorFactory.java
> +            providedChecksumsSources, "provided checksum sources cannot be null "
Trailing space

2022-01-30 15:37 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java
> +        @Named( FileProvidedChecksumSource.NAME ) ProvidedChecksumsSource fileDownloadChecksumSource
Is `fileDownloadChecksumSource` still correct?

2022-01-30 15:37 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java
> +        Map<String, ProvidedChecksumsSource> downloadChecksumSources = new HashMap<>();
Same here

2022-01-30 15:37 UTC, michael-o commented on maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/checksum/ChecksumPolicy.java
> +         * known as "smart checksums".
I wouldn't really use the term "smart chksm" in a new documentation because there is nothing smart about it.

2022-01-30 15:37 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumSource.java
> +public final class FileProvidedChecksumSource
`FileProvidedChecksumsSource`

2022-01-30 15:37 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumSource.java
> +    static final String CONFIG_PROP_BASE_DIR = "aether.artifactResolver.providedChecksumSource.file.baseDir";
`providedChecksumsSource`

2022-01-30 15:37 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumSource.java
> + * {@code maven-metadata-local.xml.sha1} in case of SHA-1 checksum).
Isn't this rather `{repoId}` depending where the data came from?

2022-01-30 15:37 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumSource.java
> +            checksumLocations.add( new ChecksumLocation(
Hmm, I confused this `ChecksumLocation` with the public one...

2022-01-30 16:35 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumSource.java
> + * {@code maven-metadata-local.xml.sha1} in case of SHA-1 checksum).
Yes, but as I have to "misuse" SimpleLRM, I think this is acceptable compromise. Also, am still not 100% sure do we really want to provide checksums for metadata (!)... At worst, this branch will not be as much used as artifact branch

2022-01-30 19:18 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumSource.java
> + * {@code maven-metadata-local.xml.sha1} in case of SHA-1 checksum).
there is no checksum for a local file:
```
$ find . -name maven-metadata\*.xml.\* -type f -exec basename {} \; | sort -u
maven-metadata-apache.snapshots.https.xml.sha1
maven-metadata-apache.snapshots.xml.sha1
maven-metadata-central-mirror.xml.sha1
maven-metadata-central.xml.sha1
maven-metadata-dynamowerk-public.xml.sha1
maven-metadata-jboss.release.xml.sha1
maven-metadata-lda-public.xml.sha1
maven-metadata-maven-core-it.xml.sha1
maven-metadata-nexus-dynamowerk-berlin.xml.sha1
maven-metadata-nexus-dynamowerk-berlin.xml.sha256
maven-metadata-nexus-dynamowerk-berlin.xml.sha512
maven-metadata-public.xml.sha1
maven-metadata-repository.jboss.org.xml.sha1
maven-metadata-snapshot-repository.xml.sha1
maven-metadata-sonatype-nexus-snapshots.xml.sha1
maven-metadata-sonatype.xml.sha1
maven-metadata-tesla.xml.part
maven-metadata-tesla.xml.part.lock
```
and
```
$ find . -name maven-metadata\*.xml -type f -exec basename {} \; | sort -u
maven-metadata-apache.snapshots.https.xml
maven-metadata-apache.snapshots.xml
maven-metadata-central-mirror.xml
maven-metadata-central.xml
maven-metadata-dynamowerk-public.xml
maven-metadata-jboss.release.xml
maven-metadata-lda-public.xml
maven-metadata-lda-releases.xml
maven-metadata-local.xml
maven-metadata-maven-core-it.xml
maven-metadata-nexus-dynamowerk-berlin.xml
maven-metadata-public.xml
maven-metadata-remote.xml
maven-metadata-repository.jboss.org.xml
maven-metadata-snapshot-repository.xml
maven-metadata-sonatype-nexus-snapshots.xml
maven-metadata-sonatype.xml
```

As far as I understand, the checksum is for a remote repo and the checksum will change as soon as the metadata will change. An artifact is immutable, but the metadata is not. So you will need to update the metadata checksum everytime. I think this does not make sense. I think we should drop this.

2022-01-30 20:10 UTC, michael-o commented
Faked checksum, does not fail for me:
```
 88 [DEBUG] org.springframework.boot:spring-boot-starter-parent:pom:2.6.3 -> SHA-1:aaaaaaaabbbbffffff
 89 [INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.6.3/spring-boot-s
 90 [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.6.3/spring-boot-st
 91 [DEBUG] Writing tracking file /net/home/osipovmi/.m2/repository/org/springframework/boot/spring-boot-starter-parent/2.6.3/_remote.repositorie
 92 [DEBUG] Writing tracking file /net/home/osipovmi/.m2/repository/org/springframework/boot/spring-boot-starter-parent/2.6.3/spring-boot-starter
 93 [DEBUG] Extension realms for project com.java:build-with-deeply-structure-sentences-may-prohibilitively-slow:jar:1.0-SNAPSHOT: (none)
```

2022-01-30 20:23 UTC, michael-o requested changes

2022-01-30 20:23 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumsSource.java
> +                        if ( LOGGER.isDebugEnabled() )
This is redudant with SLF4J.

2022-01-30 20:23 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumsSource.java
> +                                    checksumFilePath.checksumAlgorithmFactory.getName(), checksum );
I think even for debugging purposes this needs more text. E.g.:

> "Resolved provided checksum '{}:{}' for '{}'"

2022-01-31 08:49 UTC, cstamas commented
Tested on https://github.com/apache/maven/pull/635

Console snippets:
```
[WARNING] Checksum validation failed, expected BAD but is cf43b5391de623b36fe066a21127baef82c64022 from walmart-grid for http://urnebes.local:8881/content/groups/wlabs/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar
...
[INFO] --------------------------------------------------------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] --------------------------------------------------------------------------------------------------------------------------
[INFO] Total time:  1.811 s
[INFO] Finished at: 2022-01-31T09:47:54+01:00
[INFO] --------------------------------------------------------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce (enforce-maven-version) on project maven-bom: Execution enforce-maven-version of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce failed: Plugin org.apache.maven.plugins:maven-enforcer-plugin:3.0.0 or one of its dependencies could not be resolved: Could not transfer artifact org.codehaus.plexus:plexus-utils:jar:3.3.0 from/to walmart-grid (http://urnebes.local:8881/content/groups/wlabs/): Checksum validation failed, expected BAD but is cf43b5391de623b36fe066a21127baef82c64022 -> [Help 1]
```

2022-01-31 09:17 UTC, michael-o requested changes

2022-01-31 09:17 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/AbstractChecksumPolicy.java
> +        if ( !kind.isIgnoreOnMismatch() )
This isn't good. We have a clear checksum policy and this defeats the policy. The source of the checksums should be irrelevant. `REMOTE` and `PROVIDED` bust be equal.

2022-01-31 09:22 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/AbstractChecksumPolicy.java
> +        if ( !kind.isIgnoreOnMismatch() )
Unsure do I get your comment: they are (they have same isIgnoreOnMismatch value -- so they are handled equally)

2022-01-31 09:27 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/AbstractChecksumPolicy.java
> +        if ( !kind.isIgnoreOnMismatch() )
I'd drop this altogether. We have a checksum policy. Not the checksum kind should decide this.

2022-01-31 10:02 UTC, michael-o approved these changes
Please squash, align commit message to "[MRESOLVER-234] Introduce "provided" checksums feature" and merge.

2022-01-31 10:08 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/AbstractChecksumPolicy.java
> +        if ( !kind.isIgnoreOnMismatch() )
https://issues.apache.org/jira/browse/MRESOLVER-237 coming next

2022-01-31 10:27 UTC, michael-o commented
MAke sure to replace TBD with 1.8.0

2022-01-31 11:25 UTC, merged

2025-06-13 08:26 UTC, jira-importer commented
Resolve #1372