Use BFS approach
apache/maven-resolver pull request #144
Opened 2022-01-12 07:14 UTC by caiwei-ebay

2022-01-12 07:24 UTC, caiwei-ebay commented
@michael-o @ibabiankou

Please help review.

2022-01-12 07:41 UTC, michael-o commented
@cstamas

2022-01-16 16:28 UTC, ibabiankou requested changes
@caiwei-ebay Thank you for working on this change! I looked at the change and believe we can do a few improvements.

1. The data required to process dependencies is scattered across `DataPool` and `DependencyNodeTraceContext`, I think the part in the pool is not needed.
2. In the current implementation `DependencyNodeTraceContext` represents all dependencies of a single node, given that down the line we want to handle those dependencies in parallel, we should already make sure one entry in the queue corresponds to one dependency. 

If you don't mind giving me write access to the fork, I'd love to collaborate and push some changes with minor improvements such as comments, formatting etc. 😉

2022-01-16 16:28 UTC, ibabiankou commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyCollector.java
> +        }
IIUC this can not happen.

2022-01-17 03:41 UTC, caiwei-ebay commented
@ibabiankou 

Thanks for your valuable feedbacks!
Added you as admin of my forked repo, please go ahead with your changes.

2022-01-18 01:53 UTC, caiwei-ebay commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DataPool.java
> +                                    boolean recursive )
recursive was there in the original implementation, is it safe to remove that?

2022-01-18 01:54 UTC, caiwei-ebay commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyCollector.java
> +        }
Maybe not safe to remove as recursive was there in the original implementation.

2022-01-18 01:55 UTC, caiwei-ebay commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyCollector.java
> +            //Should not cache the children of root node just like original DFS solution
One test would fail if you remove this and original DFS solution did not cache the children of root node.

2022-01-19 22:37 UTC, ibabiankou commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DataPool.java
> +                                    boolean recursive )
When `recursive` of original implementation is `false`, the instance of this context is not created, so this one is always `true`.

2022-01-19 22:39 UTC, ibabiankou commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyCollector.java
> +            //Should not cache the children of root node just like original DFS solution
I moved the caching logic back to the place where it used to be, it makes smaller diff and simplifies the review.

2022-01-19 22:42 UTC, ibabiankou commented
@caiwei-ebay FYI: I've pushed some changes, but a few of the original comments are still to be addressed. I also want to have a fresh look at the naming and javadoc after that. I'll try to wrap it up tomorrow.

2022-01-21 11:05 UTC, ibabiankou commented
@caiwei-ebay I'd say the PR is ready for review from my perspective. Below are the suggested title and description for the PR. WDYT?

`Collect dependencies in breadth-first order`

```
This PR changes dependency processing order from depth-first to breadth-first as a preparation for further improvements (MRESOLVER-228, MRESOLVER-7).

**Key changes**
1. NodeStack.find moved to DefaultDependencyCycle since the NodeStack is replaced with a List in the DependencyProcessingContext.
2. Args.dependencyProcessingQueue contains a DependencyProcessingContext for each dependency that should be collected.

Note: This PR does not solve the MRESOLVER-133, though one could expect so from the titles. The main goal of the ticket is to implement early exit when resolving the version range. The ticket should be updated to reflect that.
```

@michael-o @cstamas I was thinking about rewriting the history of changes to make review easier, however, the only split that makes sense to me is 
1. Use breadth-first order (add the new context and use it) ~95% of the change
2. Move the `find` method to DefaultDependencyCycle and drop NodeStack

And it doesn't seem to make the review much easier 😕 

Given that the change is fairly small and the majority of the diff is due to moving the `find` and adding `context.` to access the same things from the new place, do you think it is worth the effort?

2022-01-21 13:21 UTC, michael-o commented
@ibabiankou  No need to squash at this stage. Pleease make are resolved discussions as such. Waiting for @caiwei-ebay Confirmation that this is ready to review.

2022-01-21 19:25 UTC, ibabiankou commented
>Pleease make are resolved discussions as such.

Unfortunately, I can not do that. Looks like I don't have some permissions or something. 

<img width="819" alt="Screenshot 2022-01-21 at 20 24 57" src="https://user-images.githubusercontent.com/5629010/150588014-6bfea1c4-c332-4973-b4d8-bc2faf5ab439.png">

2022-01-23 12:40 UTC, caiwei-ebay commented
@michael-o 

All the changes @ibabiankou  made are good to me. Thanks @ibabiankou! 
Please go ahead for the next process.

2022-01-25 12:01 UTC, ibabiankou approved these changes
LGTM 🎉😊

2022-01-25 12:21 UTC, michael-o commented
Thanks you guys, I will pick this up by the end of the week.

2022-01-27 20:45 UTC, michael-o commented
First and foremost question: Does this implement MRESOLVER-133?

2022-01-27 20:49 UTC, michael-o reviewed
* Guys, can you verbally express what you change actually does?
* Does it incur any resolution result changes? If not, can this be tested some how?

2022-01-27 20:49 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyCollector.java
> +                if ( cycleEntry != -1 )
Why not retain `>= 0`?

2022-01-28 02:14 UTC, caiwei-ebay commented
> 
@michael-o @ibabiankou 
This PR does not solve the MRESOLVER-133, though one could expect so from the titles. The main goal of this PR is to implement pure BFS approach which is the prerequisite for:

- implement early exit when resolving the version range. MRESOLVER-133
- implement a skip approach to avoid unnecessary version resolution. MRESOLVER-228
- implement parallel downloadning, MRESOLVER-7

2022-01-28 02:16 UTC, caiwei-ebay commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyCollector.java
> +                if ( cycleEntry != -1 )
They are totally the same, I reverted the change. Thanks for pointing out.

2022-01-28 02:24 UTC, caiwei-ebay commented
> 
@michael-o 
Guys, can you verbally express what you change actually does?

A: This PR is pure BFS approach. Just a change from DFS -> BFS for future PRs related  MRESOLVER-133,  MRESOLVER-228 and  MRESOLVER-7.

With DFS, maven resolves all nodes to compute the dependency tree.
With this BFS solution, it still resolves all nodes to compute the dependency tree.

Later, I would like to submit a PR to skip certain nodes resolving to improve performance.

Does it incur any resolution result changes? If not, can this be tested some how?

A: Nope, it won't introduce any resolution result changes. No tests broken.
Regarding the test,  I have dryrun large number of apps in our company by comparing dependency tree and dependency list, no issues found. Not sure if this is the right test method your are expecting.

2022-01-31 18:45 UTC, cstamas commented
pls incorporate latest master changes (whether rebase+squash+force push or just merge)

2022-02-01 02:20 UTC, caiwei-ebay commented
> pls incorporate latest master changes (whether rebase+squash+force push or just merge)

@cstamas @michael-o @ibabiankou 
Rebased & squashed commits.

2022-02-08 01:54 UTC, caiwei-ebay commented
@cstamas 

Looks like the pipeline has broken since https://github.com/apache/maven-resolver/commit/280753874e4d676fb61f7d84c470c35bdb3552e3, could you please fix the issue in master branch?

2022-02-17 09:25 UTC, caiwei-ebay commented
@michael-o @cstamas 

Saw the master branch has been fixed already. Just rebased the code. 
Please let me know if there is any else I can help.

After this PR merged,  I would submit PR  for below JIRA:
- Skip & Reconcile - avoid unnecessary version resolution (MRESOLVER-228)

Then I think @ibabiankou would submit PR for:

- Download descriptors in parallel (MRESOLVER-7)

2022-02-17 12:26 UTC, cstamas commented
Tested locally. This is what I did (used Java 11 Temurin for all, on Linux):
* built and installed locally maven master branch (0be5e406d78062b56b32644fefce2642f5eab650) -- this is REFERENCE (uses resolver 1.7.3)
* built locally this PR (resolver-bfs)
* built locally and installed this maven PR https://github.com/apache/maven/pull/635 -- produces maven using resolver-1.8.0-SNAPSHOT-BFS (also uses transport-http instead of wagon, but this is irrelevant now)

Then I went back to maven master (0be5e406d78062b56b32644fefce2642f5eab650) and built it with two contenders, always using EMPTY local repository. Expectation was that build should succeed in both cases, and both should produce same local repository.

Results:
$ find local-repository/ -type f | wc -l
4442
$ du -sh local-repository/
175M	local-repository/
$

Same in both cases.

2022-02-17 12:33 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyCollector.java
> +        public void addException( Dependency dependency, Exception e, List<DependencyNode> nodes )
The new type of `nodes` now allows enhanced `for` below, no need for `int i`

2022-02-17 12:34 UTC, cstamas commented
IMHO, this looks good

2022-02-21 08:55 UTC, caiwei-ebay commented
@michael-o 
MRESOLVER-240 is fired for this PR. Please check.

2022-02-21 10:06 UTC, michael-o commented
Thank you, assigned. Will pick up next week.

2022-03-05 22:21 UTC, closed without merging