[MRESOLVER-248] Make BF and DF collectors coexists
apache/maven-resolver pull request #161
Opened 2022-04-04 15:29 UTC by cstamas

Revive replaced DF collector, and make them coexists. Default one is "old" DF, while new BF may be activated on demand (based on session config).

---

https://issues.apache.org/jira/browse/MRESOLVER-248

2022-04-04 15:41 UTC, cstamas commented
@caiwei-ebay ping

2022-04-04 18:57 UTC, cstamas commented
I think I collapsed/deduped mostly what was obvious...

2022-04-04 19:17 UTC, michael-o requested changes

2022-04-04 19:17 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java
> +        Map<String, DependencyCollectorDelegate> providedChecksumsSource = new HashMap<>();
`providedChecksumsSource` copy and paste?

2022-04-04 19:17 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/CachingArtifactTypeRegistry.java
> +public class CachingArtifactTypeRegistry
If this is logically internal, you should document it as such.

2022-04-04 19:17 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DataPool.java
> +public final class DataPool
If this is logically internal, you should document it as such.

2022-04-04 19:17 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyCollectionContext.java
> +public final class DefaultDependencyCollectionContext
If this is logically internal, you should document it as such.

2022-04-04 19:17 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyCycle.java
> +public final class DefaultDependencyCycle
If this is logically internal, you should document it as such.

2022-04-04 19:17 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyGraphTransformationContext.java
> +public class DefaultDependencyGraphTransformationContext
If this is logically internal, you should document it as such.

2022-04-04 19:17 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultVersionFilterContext.java
> +public final class DefaultVersionFilterContext
If this is logically internal, you should document it as such.

2022-04-04 19:17 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java
> +                requireNonNull( remoteRepositoryManager, "remote repository provider cannot be null" );
Not provider, manager

2022-04-04 19:17 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfProcessingContext.java
> +final class BfProcessingContext
`BfDependencyProcessingContext`?

2022-04-05 06:33 UTC, cstamas commented
General remark: the convention to name package as "internal" or "impl" should automatically imply this is INTERNAL thing (AFAIK, some OSGi tooling and Takari life-cycle even enforce this). In this case we deal with "internal.impl" :smile: so IMHO it should be really really clear to developer that this is internal implementation... Am just saying this is something generally used, but agree, will update javadoc

2022-04-05 06:49 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java
> +        Map<String, DependencyCollectorDelegate> providedChecksumsSource = new HashMap<>();
fixed

2022-04-05 06:49 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/CachingArtifactTypeRegistry.java
> +public class CachingArtifactTypeRegistry
fixed

2022-04-05 06:50 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DataPool.java
> +public final class DataPool
fixed

2022-04-05 06:50 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyCollectionContext.java
> +public final class DefaultDependencyCollectionContext
fixed

2022-04-05 06:50 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyCycle.java
> +public final class DefaultDependencyCycle
fixed

2022-04-05 06:50 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultVersionFilterContext.java
> +public final class DefaultVersionFilterContext
fixed

2022-04-05 06:50 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java
> +                requireNonNull( remoteRepositoryManager, "remote repository provider cannot be null" );
fixed

2022-04-05 06:51 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfProcessingContext.java
> +final class BfProcessingContext
Named it as DependencyProcessingContext as it is already BF specific (same naming pattern that Skipper has)

2022-04-05 06:54 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyGraphTransformationContext.java
> +public class DefaultDependencyGraphTransformationContext
Fixed

2022-04-07 06:26 UTC, cstamas commented
@michael-o any blocker here?

2022-04-07 06:26 UTC, cstamas commented
@caiwei-ebay all looking good here? Any proposal to change/add?

2022-04-07 06:28 UTC, michael-o commented
Will review today/tomorrow.

2022-04-07 08:16 UTC, caiwei-ebay commented
> @caiwei-ebay all looking good here? Any proposal to change/add?

Looks good to me. Thanks.

2022-04-08 03:58 UTC, kwin commented
Can you outline how to toggle at https://github.com/apache/maven-resolver/blob/master/src/site/markdown/configuration.md?

2022-04-08 05:45 UTC, cstamas commented
Right, doco changes are missing (2 new config keys), will add them

2022-04-08 08:50 UTC, michael-o requested changes

2022-04-08 08:50 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java
> +        bind( DependencyCollectorDelegate.class ).annotatedWith( Names.named( BfDependencyCollector.NAME ) )
Why delegate and not `DependencyCollector` directly?

2022-04-08 08:50 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java
> + * Helper class for delegate implementations, they should subclass this class.
Should or must? If they don't they aren't registered, no?

2022-04-08 08:50 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
> +    public static final String CONFIG_PROP_USE_SKIP = "aether.dependencyCollector.bf.useSkip";
I think this should be `.skipper` since we don't use imperative verbs in other boolean flags.

2022-04-08 08:50 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
> +        logger.debug( "Dependency collection stats {}", stats );
Do you we really need a map here and the object creation? The ouput also lacks a unit which makes it hard to read. Maybe:

```
logger.debug( "Dependency collection stats: collect time: {} ms, transform time {} ms", toMS(time2 - time1), toMS(time3 - time2));
```

2022-04-08 08:50 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
> +                                                               + ": " + e.getMessage(), e );
Let's drop `e.getMessage()`, it is duplicated.

2022-04-08 08:50 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/DependencyResolutionSkipper.java
> +     * Cache the resolution result when a node is resolved by @See DependencyCollector after resolution.
`@See` is broken

2022-04-08 08:50 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
> +        logger.debug( "Dependency collection stats {}", stats );
Same here. Plus, `DefaultDependencyCollector` isn't correct anymore.

2022-04-08 08:50 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
> +                                                               + ": " + e.getMessage(), e );
Same here.

2022-04-08 08:50 UTC, michael-o commented on src/site/markdown/configuration.md
> +`aether.dependencyCollector.impl` | String | The name of the dependency collector implementation to use: depth-first (original) named `df`, and breadth-first (new in 1.8) named `bf`. Both collectors
1.8.0

2022-04-08 09:09 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java
> +        bind( DependencyCollectorDelegate.class ).annotatedWith( Names.named( BfDependencyCollector.NAME ) )
The would cause a cycle in DefaultDependencyCollector, would try to inject itself into itself... this is the usual patter: subclass the iface and inject that.

2022-04-08 09:10 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java
> + * Helper class for delegate implementations, they should subclass this class.
Must, yup, this is the actual type being injected so yes, must.

2022-04-08 09:30 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
> +        logger.debug( "Dependency collection stats {}", stats );
this map is sent for a trip around the world (conflict sorter, conflict marker, conflict resolver), and THEN is populated with these two keys and logged. And everything logs in nanos. I am leaving this as is, will put it into `if log.isDebugEnabled` instead for now, but reworking all these to not log in nanos but in ms is IMHO out of the scope of this PR. Also, this is very very technical log output, so I'd not bother making it readable or whatnot.

2022-04-08 09:31 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
> +        logger.debug( "Dependency collection stats {}", stats );
Same here: this map is sent for a trip around the world (conflict sorter, conflict marker, conflict resolver), and THEN is populated with these two keys and logged. And everything logs in nanos. I am leaving this as is, will put it into `if log.isDebugEnabled` instead for now, but reworking all these to not log in nanos but in ms is IMHO out of the scope of this PR. Also, this is very very technical log output, so I'd not bother making it readable or whatnot.

2022-04-08 09:31 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
> +                                                               + ": " + e.getMessage(), e );
am unsure is changing log output in scope of this PR

2022-04-08 09:32 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
> +                                                               + ": " + e.getMessage(), e );
am unsure is changing log/exception output in scope of this PR

2022-04-08 09:33 UTC, cstamas commented on src/site/markdown/configuration.md
> +`aether.dependencyCollector.impl` | String | The name of the dependency collector implementation to use: depth-first (original) named `df`, and breadth-first (new in 1.8) named `bf`. Both collectors
fixed

2022-04-08 09:33 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
> +                                                               + ": " + e.getMessage(), e );
fixed

2022-04-08 09:34 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/DependencyResolutionSkipper.java
> +     * Cache the resolution result when a node is resolved by @See DependencyCollector after resolution.
fixed

2022-04-08 09:34 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
> +                                                               + ": " + e.getMessage(), e );
fixed

2022-04-08 09:34 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
> +    public static final String CONFIG_PROP_USE_SKIP = "aether.dependencyCollector.bf.useSkip";
fixed

2022-04-08 09:44 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java
> +        bind( DependencyCollectorDelegate.class ).annotatedWith( Names.named( BfDependencyCollector.NAME ) )
Makes sense,

2022-04-08 09:44 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
> +        logger.debug( "Dependency collection stats {}", stats );
Agreed.

2022-04-08 09:49 UTC, michael-o requested changes
Almost done. Will run tests.

2022-04-08 09:49 UTC, michael-o commented on maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollectorTest.java
>      public void setupCollector( boolean useSkip )
`useSkip` => `useSkipper`?

2022-04-08 09:49 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
> +            stats.put( "BfDependencyCollector.transformTime", time3 - time2 );
Stupid question: If you already have the logger class name in the ouput, if necessary, why print it again here?

2022-04-08 09:50 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
> +            stats.put( "BfDependencyCollector.transformTime", time3 - time2 );
am unsure does Maven uses "standard" layout w/ classes... is it? I'd just don't bother :smile:

2022-04-08 09:52 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
> +            stats.put( "BfDependencyCollector.transformTime", time3 - time2 );
Yes, you can easily enable with SLF4J Simple, if necessary

2022-04-08 10:20 UTC, cstamas commented on maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollectorTest.java
>      public void setupCollector( boolean useSkip )
fixed

2022-04-08 11:14 UTC, michael-o approved these changes
Looks good now. Please squash and change title: "Make DF and BF collector implementations coexist"

2022-04-08 11:16 UTC, merged

2025-06-13 08:27 UTC, jira-importer commented
Resolve #1402