Idea2: collector using RequestTrace
apache/maven-resolver pull request #182
Opened 2022-05-24 13:50 UTC by cstamas

To pass over contextual information to listeners.

2022-05-28 20:15 UTC, michael-o requested changes
How does this change the memory usage when this type of information is collected by default?

2022-05-28 20:15 UTC, michael-o commented on maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/util/ReverseTreeRepositoryListener.java
> +            String trackingData = node.toString() + " (" + collectStepTrace.getContext() + ")\n";
`System.lineSeparator()`

2022-05-28 20:15 UTC, michael-o commented on maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/util/ReverseTreeRepositoryListener.java
> +            String trackingData = node.toString() + " (" + collectStepTrace.getContext() + ")\n";
`toString()` is redudant

2022-05-28 20:15 UTC, michael-o commented on maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/util/ReverseTreeRepositoryListener.java
> +                trackingData += indent + curr + " (" + collectStepTrace.getContext() + ")\n";
`System.lineSeparator()`

2022-05-28 20:15 UTC, michael-o commented on maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/util/ReverseTreeRepositoryListener.java
> +     * The event "artifact resolved" if fired WHENEVER an artifact is resolved, BUT, it happens also when an artifact
BUT it...

2022-05-28 20:15 UTC, michael-o commented on maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/util/ReverseTreeRepositoryListener.java
> +     * method "filters" out in WHICH artifact are we interested in, but it intentionally neglects extension, as
extension as

2022-05-28 20:15 UTC, michael-o commented on maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/util/ReverseTreeRepositoryListener.java
> +    }
Classifier and type don't matter?

2022-05-29 17:11 UTC, cstamas commented on maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/util/ReverseTreeRepositoryListener.java
> +    }
No, it does not, as one "collect" events may produce several events, as parent POMs are being collected, and per definition parent POM GAV must be different (otherwise you have a cycle). Also, this is "demo snippet", and example here only want's to be clear that the event fired does not correspond 1:1 to "collect step" (again, several events are fired per one collect step).

The trace request is added ONLY when collecting, and these events are fired as side effects of artifact descriptor read requests, and those are going to model builder, that in turn resolve (so use cached or fetches from remote) the POM and all POMs (like parents) needed to build artifact descriptor.... Hence, unrelated to actual dependency, artifact descriptor reader effectively goes for their POMs. Also, if you think about it, any classified artifact and main one too uses same one POM.

2022-05-29 17:12 UTC, cstamas commented
> How does this change the message usage when this type of information is collected by default?

I don't quite get the question here...

2022-05-29 17:17 UTC, michael-o commented
> > How does this change the message usage when this type of information is collected by default?
> 
> I don't quite get the question here...

Stupid typo: memory usage

2022-05-29 17:18 UTC, michael-o commented on maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/util/ReverseTreeRepositoryListener.java
> +    private static final String LINE_SEP = System.lineSeparator();
In most cases we even use `LS` or `EOL`.

2022-05-29 17:26 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java
> +    protected RequestTrace collectStepTrace( RequestTrace trace, String context, List<DependencyNode> path,
Am least certain about this method: it does "too little" IMHO. For example, it could just take a copy the passed in "path" parameter list, but OTOH, am unsure how big penalty (heap, GC wise) would this introduce. Hence, am leaving this decision (to copy or not copy the list) to subclass, as subclass should know does it requires a copy or not, or in other words, is it multi threaded or not.

2022-05-29 17:32 UTC, cstamas commented
> > > How does this change the message usage when this type of information is collected by default?
> > 
> > 
> > I don't quite get the question here...
> 
> Stupid typo: memory usage

I foresee minimal change, as this does not duplicates any collection, is really just new "step" instance per collect step. Still, AFAIR @khmarbaise  had some benchmark framework, so would be good to compare on insanely huge projects I guess....

2022-05-30 19:29 UTC, michael-o commented
On my list for end of week. Waiting for @khmarbaise also...

2022-06-06 16:57 UTC, cstamas commented
@grgrzybek Please take a peek a compare the "demo snippet" output with what you need

2022-06-06 17:11 UTC, grgrzybek commented
I'll check tomorrow - thanks!

2022-06-06 17:52 UTC, michael-o approved these changes
From my PoV just fine, waiting for @grgrzybek

2022-06-09 09:04 UTC, grgrzybek commented
Dependencies can be tracked as expected. It works different for child→parent relationship, because the path is not passed down with `RequestTrace`.

Most of the projects being built on fresh repo starts with:
```
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom (3.9 kB at 8.9 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom (13 kB at 157 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom (26 kB at 277 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom (15 kB at 197 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar (25 kB at 254 kB/s)
```

However for org.apache:apache:pom:10, I could track this information (in fresh M2 repo in `org/apache/apache/10/.tracking/org.apache.maven.plugins_maven-clean-plugin_2.5.plugin` file):
```
org.apache:apache:pom:10
  org.apache.maven.plugins:maven-clean-plugin:2.5
    org.apache.maven:maven-core:3.8.6.1:default-lifecycle-bindings (implicit)

Repository: central (https://repo.maven.apache.org/maven2, default, releases)
```

It'd be great to insert these:
* org/apache/maven/plugins/maven-plugins/22
* org/apache/maven/maven-parent/21

but for now let's leave as is - parent-child relationship is much less relevant than normal dependencies.

What's most important is `log4j/log4j/1.2.12/.tracking/org.apache.maven.plugins_maven-compiler-plugin_jar_3.1.dep` file with:
```
log4j:log4j:jar:1.2.12 (compile) (plugin)
  org.apache.xbean:xbean-reflect:jar:3.4 (compile) (plugin)
    org.codehaus.plexus:plexus-container-default:jar:1.5.5 (compile) (plugin)
      org.apache.maven.plugins:maven-compiler-plugin:jar:3.1 () (plugin)

Repository: central (https://repo.maven.apache.org/maven2, default, releases)
```

2022-06-09 12:04 UTC, cstamas commented
@grgrzybek one more thing... IF you are testing already, try out new transport? :wink:

2022-06-09 12:07 UTC, grgrzybek commented
> try out new transport
darn, I always lag behind... What kind of transport? ;)

2022-06-09 12:28 UTC, grgrzybek commented
The trace shows DefaultLegacyArtifactCollector, so this may be the reason:
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.ops4j.tools.maven.tracker.TrackingRepositoryListener.write(TrackingRepositoryListener.java:123)
	  at org.ops4j.tools.maven.tracker.TrackingRepositoryListener.artifactResolved(TrackingRepositoryListener.java:52)
	  at org.eclipse.aether.internal.impl.DefaultRepositoryEventDispatcher.dispatch(DefaultRepositoryEventDispatcher.java:136)
	  at org.eclipse.aether.internal.impl.DefaultRepositoryEventDispatcher.dispatch(DefaultRepositoryEventDispatcher.java:93)
	  at org.eclipse.aether.internal.impl.DefaultArtifactResolver.artifactResolved(DefaultArtifactResolver.java:673)
	  at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:339)
	  at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:235)
	  at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:212)
	  at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:272)
	  at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:318)
	  at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:299)
	  at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:593)
	  at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:212)
	  at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:551)
	  at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:605)
	  at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect(DefaultLegacyArtifactCollector.java:148)
	  at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:504)
	  at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveWithExceptions(DefaultArtifactResolver.java:358)
	  at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:352)
	  at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:324)
	  at org.codehaus.mojo.gwt.AbstractGwtMojo.getJarAndDependencies(AbstractGwtMojo.java:377)
	  at org.codehaus.mojo.gwt.AbstractGwtMojo.getGwtDevJar(AbstractGwtMojo.java:269)
	  at com.vaadin.integration.maven.UpdateWidgetsetMojo.updateWidgetset(UpdateWidgetsetMojo.java:276)
	  at com.vaadin.integration.maven.UpdateWidgetsetMojo.updateLocalWidgetset(UpdateWidgetsetMojo.java:123)
	  at com.vaadin.integration.maven.UpdateWidgetsetMojo.doExecute(UpdateWidgetsetMojo.java:92)
	  at org.codehaus.mojo.gwt.shell.AbstractGwtShellMojo.execute(AbstractGwtShellMojo.java:182)
	  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	  at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
	  at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
	  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
	  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
	  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
	  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	  at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

2022-06-09 14:05 UTC, cstamas commented
> darn, I always lag behind... What kind of transport? ;)

Sorry, spoke too early: I just spotted you play with 3.8.6 while this is in 3.9.0 and above only https://issues.apache.org/jira/browse/MNG-7454

(you can use it with 3.8.6 as well, but is a bit more complicated, just follow steps as here https://github.com/apache/maven/pull/635)

2022-06-09 14:08 UTC, cstamas commented
Btw, Maven 3.9.0 (branch maven-3.9.x) is almost done, should be safe to use as well as you locally build instance for yourself (that's what I use as well when testing stuff).

2022-06-09 14:11 UTC, grgrzybek commented
> Btw, Maven 3.9.0 (branch maven-3.9.x) is almost done, should be safe to use as well as you locally build instance for yourself (that's what I use as well when testing stuff).

Will it use maven resolver 1.8.0 or 1.8.1?
Any chance this PR will make it into maven-resolver used in Maven 3.9.0?

2022-06-09 14:12 UTC, cstamas commented
> Will it use maven resolver 1.8.0 or 1.8.1? Any chance this PR will make it into maven-resolver used in Maven 3.9.0?

Yes and yes: this is last bit we waited for to release resolver 1.8.1, and hopefully will go into Maven 3.9.0.

2022-06-09 14:17 UTC, cstamas commented
> From my PoV just fine, waiting for @grgrzybek

In a moment you nod, am merging this and soon is followed by 1.8.1 release...

2022-06-09 15:07 UTC, grgrzybek approved these changes

2022-06-09 19:10 UTC, michael-o commented
@grgrzybek can we merge this?

2022-06-09 19:26 UTC, merged

2022-06-10 04:40 UTC, grgrzybek commented
@michael-o sorry for holding the release - I added my approval earlier ;)

2025-06-13 08:05 UTC, jira-importer commented
Resolve #910

2025-06-13 08:05 UTC, jira-importer commented
Resolve #910