[MRESOLVER-274] Remote Repository Filter
apache/maven-resolver pull request #197
Opened 2022-09-16 19:27 UTC by cstamas

RemoteRepository filter feature and some demo (so far) code.

---

https://issues.apache.org/jira/browse/MRESOLVER-274

2022-09-20 19:44 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/RemoteRepositoryFilterSourceSupport.java
> +        return (RemoteRepositoryFilter) session.getData().computeIfAbsent( configPropKey( CONF_NAME_INSTANCE ), () ->
This is unneeded, mgr caches managed instace

2022-09-20 19:45 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/RemoteRepositoryFilterSourceSupport.java
> +     * Implementing classes in this method must return non-null implementation of filter (as enabled was checked
This is untrue, implementation STILL MAY decide to return null, manager will handle it.

2022-10-06 12:30 UTC, cstamas commented
Remarks:
* rework "recording" feature using upcoming https://github.com/apache/maven-resolver/pull/200 feature to record "exact facts", as current recording has several issues and records a lot of noise.
* maybe files can be renamed? According to this https://github.com/cstamas/rrf-demo#what-is-happening-part-2 the layout is a bit redundant ("prefix/prefixes-..." and "groupId/groupId-...."). Either put them level higher with same name, or keep them separated by then remove redundant prefix?

2022-10-07 08:47 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/RemoteRepositoryFilterSourceSupport.java
> + * like optional "bqsedir" calculation, handling of "enabled" flag.
fixed

2022-10-08 08:35 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +                            filterResult.reasoning() ) );
Is this really worth an exception? I mean if I know that my repo will only serve `com.example` it is not an error to skip `org` for reason.

2022-10-08 08:36 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +                    && !remoteRepositories.equals( filteredRemoteRepositories );
Do we really have `#equals()` implemented on repo level?

2022-10-08 08:39 UTC, michael-o requested changes

2022-10-08 08:39 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +                    && !remoteRepositories.equals( filteredRemoteRepositories );
What if all repos are eligible to serve a specific artifact?

2022-10-08 08:39 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultMetadataResolver.java
> +                result.setException( new MetadataNotFoundException( metadata, repository, filterResult.reasoning() ) );
Same as above.

2022-10-08 08:45 UTC, michael-o commented
General question: Is it intended to plugin with Maven repo definition in POM and settings to have nested elements `<includes />`/`<excludes />`? Similar to maven-common-artifact-filters. This would be easily accessible, but requires model changes and would work without any brainfuck for the users. https://issues.apache.org/jira/browse/MNG-6763

2022-10-08 09:21 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +                            filterResult.reasoning() ) );
Yes, this is common way to communicate (up to the surface) why resolution failed, see here https://github.com/apache/maven-resolver/blob/master/maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java#L380-L384 and here https://github.com/apache/maven-resolver/blob/master/maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java#L418-L425 and here https://github.com/apache/maven-resolver/blob/master/maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultMetadataResolver.java#L222

2022-10-08 09:22 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +                    && !remoteRepositories.equals( filteredRemoteRepositories );
Yes, see here https://github.com/apache/maven-resolver/blob/master/maven-resolver-api/src/main/java/org/eclipse/aether/repository/RemoteRepository.java#L265-L300  (and it is a `final` class on purpose as well)

2022-10-08 09:22 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +                    && !remoteRepositories.equals( filteredRemoteRepositories );
then `filteringApplied` is `false`?

2022-10-08 09:22 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultMetadataResolver.java
> +                result.setException( new MetadataNotFoundException( metadata, repository, filterResult.reasoning() ) );
Same as "see here, and here and here"

2022-10-08 09:26 UTC, cstamas commented
> General question: Is it intended to plugin with Maven repo definition in POM and settings to have nested elements `<includes />`/`<excludes />`? Similar to maven-common-artifact-filters. This would be easily accessible, but requires model changes and would work without any brainfuck for the users. https://issues.apache.org/jira/browse/MNG-6763

This is maven-resolver, not maven. Hence, one can consier this as "foundation" (low level) implementation, that can be topped in many different ways, for example, Maven could either provide it's own filter implementations sourced from new model (if model is changed to support that) or just "manage" these "low level" sources in some way. This PR is not related in any way to Maven, as it have no access to models like POM, Settings, etc. It just lies down the foundations to solve that issue.

2022-10-08 09:27 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +                            filterResult.reasoning() ) );
Also, see here https://github.com/apache/maven-resolver/blob/master/maven-resolver-api/src/main/java/org/eclipse/aether/resolution/ArtifactResolutionException.java#L96

2022-10-11 07:22 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +                    && !remoteRepositories.equals( filteredRemoteRepositories );
meanng: all works as before (today)

2022-10-11 07:45 UTC, cstamas commented
@michael-o rebased

2022-10-22 16:25 UTC, gnodet commented on src/site/markdown/remote-repository-filtering.md
> +plugin depends on filtered artifact).
Would it be possible to add a `How?` section briefly explaining how to set up RRF ?

2022-10-22 16:26 UTC, gnodet approved these changes

2022-10-25 08:25 UTC, cstamas commented on src/site/markdown/remote-repository-filtering.md
> +plugin depends on filtered artifact).
I plan to extend doco, probably to reuse this "demo" (not code but text from it): https://github.com/cstamas/rrf-demo

2022-10-25 15:13 UTC, gnodet requested changes

2022-10-25 15:13 UTC, gnodet commented on src/site/markdown/remote-repository-filtering.md
> +directory, and will refer to it in this document with `${filterBasedir}` placeholder.
`directory, and will refer to it in` -> `directory. It will be referred to in`

2022-10-25 19:57 UTC, gnodet approved these changes

2022-10-25 20:11 UTC, merged

2025-06-13 08:05 UTC, jira-importer commented
Resolve #901

2025-06-13 08:38 UTC, jira-importer commented
Resolve #901