Simplify and fix trusted checksum sources.
apache/maven-resolver pull request #203
Opened 2022-10-17 09:32 UTC by cstamas

Changes:
* support class meddles less re basedir
* sparse source: use `fileProcessor` to read and write checksums (not mix fileProcessor and Files.write), better handle basedir
* summary source: clearly split "record" and non-recording, enhance Writer, add "truncateOnSave" (otherwise merge existing checksums)

2022-10-18 09:23 UTC, michael-o requested changes

2022-10-18 09:23 UTC, michael-o commented on maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
> +        Files.createDirectories( target.getParent() );
Why not use `parent` here?

2022-10-18 09:23 UTC, michael-o commented on maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
> +        Path parent = requireNonNull( target.getParent(), "target must be a file" );
I don't understand this message

2022-10-18 09:30 UTC, cstamas commented on maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
> +        Files.createDirectories( target.getParent() );
fixed

2022-10-18 09:33 UTC, cstamas commented on maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
> +        Path parent = requireNonNull( target.getParent(), "target must be a file" );
https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#getParent--

On unix, "/foo" has a parent "/" while "/" has no parent (null is returned). Unsure what happens on non-OSes though. Point here is to not use this method with `target="/"` but only `target="/foo"`, that target path must have parent.

2022-10-18 09:46 UTC, michael-o commented on maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
> +        Path parent = requireNonNull( target.getParent(), "target must be a file" );
Ah OK, now this is clear.

2022-10-22 18:00 UTC, gnodet approved these changes

2022-10-23 09:32 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/FileTrustedChecksumsSourceSupport.java
> +        return ConfigUtils.getBoolean( session, true, configPropKey( CONF_NAME_ORIGIN_AWARE ) );
Does this really make sense since we don't split artifacts by repo neither?

2022-10-23 09:32 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/SummaryFileTrustedChecksumsSource.java
> + * written checksums will become visible only for writer session, and newly written checksums, if any, will be flushed
So this is not really per physical file and NOT per GAV?

2022-10-25 07:02 UTC, cstamas commented on maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/checksum/FileTrustedChecksumsSourceTestSupport.java
> +    protected abstract void enableSource( DefaultRepositorySystemSession session );
You did, the session passed as param is used, may make support session private to make it more obvious

2022-10-25 07:05 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/FileTrustedChecksumsSourceSupport.java
> +        return ConfigUtils.getBoolean( session, true, configPropKey( CONF_NAME_ORIGIN_AWARE ) );
This has nothing to do with LRM and are they split or not. This way you just say "junit 4.13.2 from central has sha-1 8ac9e16d933b6fb43bc7f576336b8f4d7eb5ba12" and turn on "fail if missing" and you are done. Or in other words, this makes possible to maintain lists of checksums "by origin" that is IMHO simper than "in bulk", where list would be project specific, while this way, those lists are reusable across projects. 

Again, this is just a default, and while I do see valid points for both (per-origin and in-bulk), it can be easily overriden,

2022-10-25 07:08 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/SummaryFileTrustedChecksumsSource.java
> + * written checksums will become visible only for writer session, and newly written checksums, if any, will be flushed
As explained above, summary contains a list of file -> checksum for given algorithm (one file is one algorithm). Moreover, the default is "origin aware", so that above is really "list of files -> checksum for given algorith per repository".

Actually am unsure what you ask here, "not per file and not per gav"? What is it then?

2022-10-25 07:09 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/SummaryFileTrustedChecksumsSource.java
> + * written checksums will become visible only for writer session, and newly written checksums, if any, will be flushed
Well, previously it contained coordinates. Just wanted to understand the change. No more, no less.

2022-10-25 07:09 UTC, michael-o approved these changes

2022-10-25 07:20 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/SummaryFileTrustedChecksumsSource.java
> + * written checksums will become visible only for writer session, and newly written checksums, if any, will be flushed
This is basically what I understood.

2022-10-25 07:33 UTC, cstamas commented on maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/checksum/FileTrustedChecksumsSourceTestSupport.java
> +    protected abstract void enableSource( DefaultRepositorySystemSession session );
see c87798a898f45d1d4998b5c9146fa0f2fa06c3cd

2022-10-25 08:23 UTC, merged

2025-06-13 08:07 UTC, jira-importer commented
Resolve #953

2025-06-13 08:38 UTC, jira-importer commented
Resolve #953