Expand use of atomic file ops
apache/maven-resolver pull request #218
Opened 2022-11-11 13:45 UTC by cstamas

Drop old and legacy code doing smart(er) things, use common shared primitives instead.

2022-11-11 19:15 UTC, michael-o requested changes

2022-11-11 19:15 UTC, michael-o commented on maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
> +     * A collocated temporary file, that resides next to a "target" file, and is removed when closed.
colocated and not collocated?!

2022-11-12 12:25 UTC, cstamas commented on maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnector.java
> -                fileProcessor.move( tmp, file );
Yes, is unused (connector was only one using it), hence I deprecated it (as it is in SPI that is public layer)

2022-11-12 12:34 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultFileProcessor.java
> +        FileUtils.writeFile( target.toPath(), p -> Files.write( p, data.getBytes( StandardCharsets.UTF_8 ) ) );
I would actually go other way around: make almost everything use FileProcessor (and extend it with some of things coming from FileUtils), as FileProcessor is a component, and hence, is replaceable. So, one could if needed, wrap the original component and "listen" for file changes happening. This is impossible with static helper....

2022-11-12 20:13 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultFileProcessor.java
> +        FileUtils.writeFile( target.toPath(), p -> Files.write( p, data.getBytes( StandardCharsets.UTF_8 ) ) );
Not now but in near future https://issues.apache.org/jira/browse/MRESOLVER-295

2022-11-12 22:23 UTC, slawekjaranowski commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultFileProcessor.java
> +    @Deprecated
We should add description - why is deprecated, what replacement ... and so.
later nobody will remember a reason

2022-11-12 22:27 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultFileProcessor.java
> +    @Deprecated
I undid deprecation

2022-11-12 22:28 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultFileProcessor.java
> +    @Deprecated
Or missed this one?

2022-11-13 14:35 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultFileProcessor.java
> +    @Deprecated
fixed

2022-11-13 14:41 UTC, cstamas commented
There's much more to do, but am stopping here due https://issues.apache.org/jira/browse/MRESOLVER-295.
My plan is following:
* component should use component (even if trivial as Slawek noted) to perform IO. Reason: components can be swapped out
* split FileProcessor into PathProcessor (as name says, for files) and ChecksumProcessor (to read write checksums ONLY, to not mix concerns). This opens up the possibility to implement different ChecksumWriters (BSD/GNU/whatever), as currently we read BSD/GNU/resolver-native but write only resolver-native format.
* but, due module layout (SPI not depending on Utils, and both Impl and Connector depending on SPI but Connector not on Impl) this needs a bit more work: see how many implementations of FileProcessor we have across, exactly for this reason. So, I want to do something with it.
* direct use of static helper reduces testability, there is a nice test where file copy fails, that cannot be done if directly static helper used.

2022-11-13 16:07 UTC, slawekjaranowski approved these changes

2022-11-14 08:29 UTC, michael-o requested changes

2022-11-14 08:29 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultFileProcessor.java
> +        FileUtils.writeFile( target.toPath(), p -> Files.copy( source, p ) );
Do we actually need oneline wrappers for `Files` at all?

2022-11-14 08:29 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultTrackingFileManager.java
> +                LOGGER.warn( "Failed to read tracking file '{}'", file, e );
This pattern should be then consistent throughout, means file param should be always in single quotes.

2022-11-14 08:29 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultTrackingFileManager.java
>      public Properties update( File file, Map<String, String> updates )
Since this is run under `SyncContext` it is guaranteed to be locked, so atomic moves aren't required?!

2022-11-14 09:39 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultTrackingFileManager.java
>      public Properties update( File file, Map<String, String> updates )
Atomic files are not to circumvent locking at all, they are to guarantee that all (like downloads) are "all or nothing" even in case of errors, resolver will not leave partially written file under any circumstances (as partially written tmp file is deleted if fails).

2022-11-14 09:41 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultFileProcessor.java
> +        FileUtils.writeFile( target.toPath(), p -> Files.copy( source, p ) );
File|Utils leverages TempFile, there is no equivalent for it in Files...

2022-11-14 10:09 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultFileProcessor.java
> +        FileUtils.writeFile( target.toPath(), p -> Files.copy( source, p ) );
Right...

2022-11-14 10:09 UTC, michael-o approved these changes

2022-11-14 10:31 UTC, merged

2025-06-13 08:07 UTC, jira-importer commented
Resolve #965

2025-06-13 08:38 UTC, jira-importer commented
Resolve #965