[MRESOLVER-318] Support dynamic core count for thread config
apache/maven-resolver pull request #239
Opened 2023-02-06 10:27 UTC by cstamas

Support same type of configuration expression as Maven does for `-T` parameter, like "1.5C".

---

https://issues.apache.org/jira/browse/MRESOLVER-318

2023-02-06 10:50 UTC, michael-o commented
Will happily review.

2023-02-06 12:08 UTC, laeubi commented on maven-resolver-util/src/main/java/org/eclipse/aether/util/concurrency/ExecutorUtils.java
> +        return new ThreadPoolExecutor( poolSize, poolSize, 3L, TimeUnit.SECONDS,
Maybe better use a work stealing pool with a concurrency level?
`java.util.concurrent.Executors.newWorkStealingPool(int)`

2023-02-06 12:16 UTC, cstamas commented on maven-resolver-util/src/main/java/org/eclipse/aether/util/concurrency/ExecutorUtils.java
> +        return new ThreadPoolExecutor( poolSize, poolSize, 3L, TimeUnit.SECONDS,
This PR is not about refactoring to work stealing pool or anything else, it literally keeps existing functionality, but merely removes copy-pasta and adds "dynamic thread count" expressions. Nothing more.

2023-02-07 10:25 UTC, michael-o requested changes
Stupid question: Since the value type has changed, how will the code react if still `int.class` is passed?

2023-02-07 10:25 UTC, michael-o commented on src/site/markdown/configuration.md
> +`aether.connector.basic.threads` or `maven.artifact.threads` | String | Number of threads to use for uploading/downloading. Accepts "dynamic" expressions like `1.5C` as well, or plain integer. | `5`
Since this is now a string the default value should be quoted just like with other string values

2023-02-07 10:25 UTC, michael-o commented on src/site/markdown/configuration.md
> +`aether.dependencyCollector.bf.threads` or `maven.artifact.threads` | String | Number of threads to use for collecting POMs and version ranges in BF collector. Accepts "dynamic" expressions like `1.5
same here

2023-02-07 10:25 UTC, michael-o commented on src/site/markdown/configuration.md
> +`aether.metadataResolver.threads` | String | Number of threads to use in parallel for resolving metadata. Accepts "dynamic" expressions like `1.5C` as well, or plain integer. | `4` | no
same here

2023-02-07 10:38 UTC, cstamas commented
> Stupid question: Since the value type has changed, how will the code react if still `int.class` is passed?

I don't quite get: passed by who?

2023-02-07 10:49 UTC, michael-o commented
> > Stupid question: Since the value type has changed, how will the code react if still `int.class` is passed?
> 
> I don't quite get: passed by who?
> 
> I mean, Maven does not interpret any of `-D` parameter values (so is and was always a String), so you must be talking about some 3rd party integration? If so, they will need to apply code changes on upgrade of resolver, but I may miss your point.

Yes, third party. I guess. But let's see.

2023-02-07 10:49 UTC, michael-o approved these changes

2023-02-07 10:54 UTC, cstamas commented
Am undoing "dynamic core count" support, hence the type change and all questionable things are gone. IMHO, the "dynamic core count" should be calculated on some higher level (app integrating resolver), not in resolver.

2023-02-07 11:01 UTC, michael-o approved these changes
Much simpler and cleaner now.

2023-02-07 11:03 UTC, merged

2025-06-13 08:08 UTC, jira-importer commented
Resolve #991

2025-06-13 08:40 UTC, jira-importer commented
Resolve #991