[MRESOLVER-328] SSL insecure mode
apache/maven-resolver pull request #255
Opened 2023-02-24 13:38 UTC by cstamas

The transport-http now has "insecure" SSL mode that simply ignores any kind of SSL validation error (trust, certificate dates, hostnames). This mode is NOT MEANT for production, as it is inherently insecure but may come handy in small shops using self signed certificates.

---

https://issues.apache.org/jira/browse/MRESOLVER-328

2023-02-24 16:32 UTC, slawekjaranowski commented
As we know that - this mode is NOT MEANT for production, 
maybe we should add a log with warning that is enabled to mitigate wrong configuration on user side

2023-02-24 17:47 UTC, cstamas commented
IMHO, having it in doco is completely enough, as on reported issue (and "smaller shops"), they may work with self signed certs, and we would just "punish" them by logging a warning in each their build log.

2023-02-24 19:22 UTC, slawekjaranowski approved these changes

2023-03-01 07:30 UTC, gnodet commented on maven-resolver-api/src/main/java/org/eclipse/aether/ConfigurationProperties.java
> +    public static final String HTTPS_INSECURE = PREFIX_CONNECTOR + "https.insecure";
Should we use a string property `https.security` with some values `secured`, `insecured` for now ? This would allow more openness for things like `no-host-verifier,no-certificate-check` ...

2023-03-01 07:30 UTC, gnodet commented on maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/GlobalState.java
> +                throw new SSLInitializationException("Could not configure 'insecure' SSL", e);
The exception message looks incoherent with the code.  We're not configuring _insecure_ ssl specifically in the code block. So I think we should either restrict the `try`/`catch` block to _insecure ssl_ configuration, or change the message.

2023-03-01 08:26 UTC, michael-o commented
> IMHO, having it in doco is completely enough, as on reported issue (and "smaller shops"), they may work with self signed certs, and we would just "punish" them by logging a warning in each their build log.

Smaller shops can add their certs into their truststores as well. IMHO,

2023-03-01 08:28 UTC, michael-o commented on maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpServer.java
> +    }
This does not make sense. How does client authentication relate to self-signed or not?

2023-03-01 08:29 UTC, michael-o commented on maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpTransporterTest.java
> +        session.setConfigProperty("aether.connector.http.ssl.insecure", true);
This is really, really ugly..., no?

2023-03-01 08:31 UTC, michael-o requested changes

2023-03-01 08:31 UTC, michael-o commented on src/site/markdown/configuration.md
> +`aether.connector.https.securityMode` | String | Using this flag resolver may set the "security mode" of HTTPS connector. Any other mode than 'default' is NOT MEANT for production, as it is inherentl
This desc does not correspond to the actual code. There are three cases, you have covered only two. You miss to cover valid before and valid after, means cert not yet valid or expired.

2023-03-01 08:53 UTC, cstamas commented on src/site/markdown/configuration.md
> +`aether.connector.https.securityMode` | String | Using this flag resolver may set the "security mode" of HTTPS connector. Any other mode than 'default' is NOT MEANT for production, as it is inherentl
W00t? There are two cases covered in code (everything else throws), and also in doco. What are you talking about exactly?

2023-03-01 08:55 UTC, cstamas commented on maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpTransporterTest.java
> +        session.setConfigProperty("aether.connector.http.ssl.insecure", true);
fixed

2023-03-01 08:55 UTC, cstamas commented on maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpServer.java
> +    }
fixed

2023-03-01 08:56 UTC, michael-o commented on src/site/markdown/configuration.md
> +`aether.connector.https.securityMode` | String | Using this flag resolver may set the "security mode" of HTTPS connector. Any other mode than 'default' is NOT MEANT for production, as it is inherentl
see: https://github.com/apache/maven-wagon/blob/aff693c6f90371aab0ae07ffcfb9bce4d3214fd1/wagon-providers/wagon-http-shared/src/main/java/org/apache/maven/wagon/shared/http/AbstractHttpClientWagon.java#L368-L370

2023-03-01 09:01 UTC, cstamas commented on src/site/markdown/configuration.md
> +`aether.connector.https.securityMode` | String | Using this flag resolver may set the "security mode" of HTTPS connector. Any other mode than 'default' is NOT MEANT for production, as it is inherentl
Still unsure what you mean: why would maven-resolver-transport-http support Wagon specific `maven.wagon.http.ssl.ignore.validity.dates`? For now we offer two "modes": default and insecure (ignores everything). If users come with this request, we will add it, but currently the code does not support this, is more like "all or nothing".

2023-03-01 09:03 UTC, cstamas commented on src/site/markdown/configuration.md
> +`aether.connector.https.securityMode` | String | Using this flag resolver may set the "security mode" of HTTPS connector. Any other mode than 'default' is NOT MEANT for production, as it is inherentl
As per @gnodet request, the "mode" is now string, so we can improve it, and even have a list like mode="ignore-cert-dates,ignore-hostname-validation", but doing that is off. What originally user asked for was support for self signed certs.

2023-03-01 09:18 UTC, michael-o requested changes

2023-03-01 09:18 UTC, michael-o commented on maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpServer.java
> +    }
Where? `addSslConnector()` still passes true.

2023-03-01 09:27 UTC, cstamas commented on maven-resolver-api/src/main/java/org/eclipse/aether/ConfigurationProperties.java
> +    public static final String HTTPS_INSECURE = PREFIX_CONNECTOR + "https.insecure";
fixed

2023-03-01 09:27 UTC, cstamas commented on maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/GlobalState.java
> +                throw new SSLInitializationException("Could not configure 'insecure' SSL", e);
fixed

2023-03-02 08:26 UTC, michael-o commented on src/site/markdown/configuration.md
> +`aether.connector.https.securityMode` | String | Using this flag resolver may set the "security mode" of HTTPS connector. Any other mode than 'default' is NOT MEANT for production, as it is inherentl
Agreed.

2023-03-02 09:10 UTC, michael-o approved these changes

2023-03-02 09:14 UTC, merged

2025-06-13 08:09 UTC, jira-importer commented
Resolve #1004

2025-06-13 08:40 UTC, jira-importer commented
Resolve #1004