[MRESOLVER-327] Allow use of system properties to configure HttpClient
apache/maven-resolver pull request #266
Opened 2023-03-07 11:03 UTC by cstamas

But do not encourage users about this, quite the opposite, drive them toward documentation how to configure transports, for example this page: https://maven.apache.org/guides/mini/guide-proxies.html

---

https://issues.apache.org/jira/browse/MRESOLVER-327

2023-03-07 12:03 UTC, kwin commented on src/site/markdown/configuration.md
> +`aether.connector.http.useSystemProperties` | boolean | If enabled, underlying Apache HttpClient will use system properties as well to configure itself (typically used to set up HTTP Proxy via Java s
I wouldn’t expect the term Maven configuration in here. Rather resolver configuration as resolver can still be used outside Maven

2023-03-07 12:06 UTC, cstamas commented on src/site/markdown/configuration.md
> +`aether.connector.http.useSystemProperties` | boolean | If enabled, underlying Apache HttpClient will use system properties as well to configure itself (typically used to set up HTTP Proxy via Java s
Originally I wanted to WARN if `proxy != null` (set few lines above), but this builder option is NOT ONLY about proxy but many many other things. Hence the hint "typically used..." as I cannot nor I want to commit to any guarantees here. Simply put: if this option used, user should use it only for "typically set" stuff, and ensure the code is doing what he things is doing.

The reason of existence of this PR is ONLY to allow use of transport-http for use case like https://issues.apache.org/jira/browse/MNG-7721 where user defines only 5 http proxy related properties.

2023-03-07 12:10 UTC, cstamas commented on src/site/markdown/configuration.md
> +`aether.connector.http.useSystemProperties` | boolean | If enabled, underlying Apache HttpClient will use system properties as well to configure itself (typically used to set up HTTP Proxy via Java s
I consider having both set an error (and at one point I had code even fail), but later realized to simple "delegate" all the responsibility to use: "user knows what he does"

2023-03-07 12:14 UTC, michael-o requested changes

2023-03-07 12:14 UTC, michael-o commented on src/site/markdown/configuration.md
> +`aether.connector.http.useSystemProperties` | boolean | If enabled, underlying Apache HttpClient will use system properties as well to configure itself (typically used to set up HTTP Proxy via Java s
The description must link to the constructor of HttpClientBuilder which will describe which properties from the system will be used.

2023-03-07 12:38 UTC, cstamas commented on src/site/markdown/configuration.md
> +`aether.connector.http.useSystemProperties` | boolean | If enabled, underlying Apache HttpClient will use system properties as well to configure itself (typically used to set up HTTP Proxy via Java s
Done

2023-03-07 14:03 UTC, cstamas commented
Am merging this as doco was updated, and is also safe as all this is disabled by default. The only reason for this change is to make possible exact use case like the reported in https://issues.apache.org/jira/browse/MNG-7721 to work with transport-http, nothing more and nothing less.

2023-03-07 14:04 UTC, merged

2025-06-13 08:09 UTC, jira-importer commented
Resolve #997

2025-06-13 08:41 UTC, jira-importer commented
Resolve #997