[MRESOLVER-346] Too eager locking in resolver
apache/maven-resolver pull request #272
Opened 2023-03-23 11:24 UTC by cstamas

The locking in resolver is too eager. This PR relaxes locking by introducing use of shared locks (not used before) and following changes:
* installer -- no change, remains exclusive locking
* deployer -- laxed to shared locking, as it only reads local repo
* A and M resolver -- implemented "upgrade", they are optimistic and start with shared lock (and will happily finish if local repo has all) but will "upgrade" to exclusive if remote access (hence local caching) is about to happen.

Best viewed with whitespace ignore, as there are not much change but blocks got nested.

---

https://issues.apache.org/jira/browse/MRESOLVER-346

2023-03-24 20:59 UTC, michael-o commented
I will review this next week

2023-03-30 19:27 UTC, slawekjaranowski commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactoryAdapter.java
> +    public static final String RETRIES_KEY = "aether.syncContext.named.retries";
New options should be add to documentation.

2023-03-30 20:42 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactoryAdapter.java
> +    public static final String RETRIES_KEY = "aether.syncContext.named.retries";
Sure, but pls consider this PR as "under testing", this is what users on ML tested (I provided them "unofficial builds" via Google Drive): https://lists.apache.org/thread/q4nlojworr8lynroyv2j0721vpmpgh70

Will add doco next.

2023-03-30 20:57 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactoryAdapter.java
> +    public static final String RETRIES_KEY = "aether.syncContext.named.retries";
Doco added

2023-04-04 18:28 UTC, michael-o commented
> The locking in resolver is too eager. This PR relaxes locking by introducing use of shared locks (not used before) and following changes:
> 
>     * installer -- no change, remains exclusive locking
> 
>     * deployer -- laxed to shared locking, as it only reads local repo
> 
>     * A and M resolver -- implemented "upgrade", they are optimistic and start with shared lock (and will happily finish if local repo has all) but will "upgrade" to exclusive if remote access (hence local caching) is about to happen.
> 
>     * syncContext adapter -- do not "hold" on acquired locks if one fails, but release all/retry all
> 
> 
> Best viewed with whitespace ignore, as there are not much change but blocks got nested.
> 
> https://issues.apache.org/jira/browse/MRESOLVER-346

So far, you explanation sounds reasonable to me. Reviewing...

2023-04-04 18:36 UTC, michael-o requested changes

2023-04-04 18:36 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +                if (!groups.isEmpty() && current == shared) {
The not empty implies that resolution is not complete?

2023-04-04 18:36 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +            while (true) {
Can we end up in an endless loop here? Whould a do while loop with a condition make more sense here? We need at least one iteration.

2023-04-04 18:36 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultDeployer.java
> +        try (SyncContext syncContext = syncContextFactory.newInstance(session, true)) {
Checksums and stuff are generated on the fly and never persisted on disk, as far as I remember?!

2023-04-04 18:36 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactoryAdapter.java
> +    public static final String RETRIES_KEY = "aether.syncContext.named.retries";
This change is for me is not related and shoud be a separate ticket and PR.

2023-04-05 05:51 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultDeployer.java
> +        try (SyncContext syncContext = syncContextFactory.newInstance(session, true)) {
yes, local repo is NOT modified, everything happens on the fly and only remote repo gets content changes

2023-04-05 05:55 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +                if (!groups.isEmpty() && current == shared) {
Yes, groups are "prepared download batches" (per remote repo, 1 or more artifact). By group being not empty, means that resolver could not fulfill resolution from local repo, hence is about to download. Here, the "downside" is that when this happens, and we switch from shared to exclusive lock, groups are rebuilt from scratch.

2023-04-05 05:57 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +            while (true) {
I don't see how: last element within this while-true loop is `return results`, meaning if we reach here even only once, we are out of the loop.

2023-04-05 05:59 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactoryAdapter.java
> +    public static final String RETRIES_KEY = "aether.syncContext.named.retries";
I argue here: this all PR is somewhat about some sort of "backoff" for locking, so IMO this change is also essential part of whole.

2023-04-05 09:16 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +                if (!groups.isEmpty() && current == shared) {
Makes sense!

2023-04-05 09:17 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactoryAdapter.java
> +    public static final String RETRIES_KEY = "aether.syncContext.named.retries";
I still don't share this opinion. While I don't object this feature as a whole, it should be visiable as as separate issue in release notes. Let's focus on too eager locking first...

2023-04-05 09:18 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
> +            while (true) {
Right.

2023-04-05 09:48 UTC, michael-o approved these changes
This looks very reasonable now to me.

2023-04-05 09:56 UTC, merged

2025-06-13 08:10 UTC, jira-importer commented
Resolve #1023

2025-06-13 08:42 UTC, jira-importer commented
Resolve #1023