Document Expected Checksums in Resolver
apache/maven-resolver pull request #281
Opened 2023-04-22 12:59 UTC by cstamas

Add documentation to new resolver transport features like "provided" and "remote included" checksums. Also explain "trusted" checksums.

2023-04-22 16:40 UTC, michael-o commented on src/site/markdown/expected-checksums.md
> +request against Artifact checksum URL (Artifact URL appended by ".sha1"). This logic
Note that this is actually transport specific.

2023-04-22 23:41 UTC, hazendaz commented on src/site/markdown/expected-checksums.md
> +means, possibly ahead of any transport operation. There is an SPI interfacce that users may
Spelling on 'interfacce' should be 'interface'

2023-04-22 23:45 UTC, hazendaz commented on src/site/markdown/expected-checksums.md
> +But the biggest game changer of Trusted Checksumms is their transport independence, that they
Spelling with 'Checksumms' should be 'Checksums'

2023-04-22 23:46 UTC, hazendaz commented on src/site/markdown/expected-checksums.md
> +the resolved artifacts againstr Truated Checksums, thus, making sure that all resolved
Few spelling issues in line 121.

2023-04-24 07:37 UTC, cstamas commented on src/site/markdown/expected-checksums.md
> +request against Artifact checksum URL (Artifact URL appended by ".sha1"). This logic
removed mention of HTTP GET

2023-04-24 07:38 UTC, cstamas commented on src/site/markdown/expected-checksums.md
> +means, possibly ahead of any transport operation. There is an SPI interfacce that users may
tx, fixed

2023-04-24 07:38 UTC, cstamas commented on src/site/markdown/expected-checksums.md
> +the resolved artifacts againstr Truated Checksums, thus, making sure that all resolved
tx, fixed

2023-04-24 07:38 UTC, cstamas commented on src/site/markdown/expected-checksums.md
> +But the biggest game changer of Trusted Checksumms is their transport independence, that they
tx, fixed

2023-04-24 07:46 UTC, michael-o requested changes

2023-04-24 07:46 UTC, michael-o commented on src/site/markdown/expected-checksums.md
> +means, possibly ahead of any transport operation. There is an SPI interface that users may
the word interface is redudant since SPI ends with interface already

2023-04-24 08:09 UTC, cstamas commented on src/site/markdown/expected-checksums.md
> +means, possibly ahead of any transport operation. There is an SPI interface that users may
changed, "SPI interface" -> "SPI extension point"

2023-04-24 08:20 UTC, michael-o commented on src/site/markdown/expected-checksums.md
> +means, possibly ahead of any transport operation. There is an SPI interface that users may
Good!

2023-04-25 21:00 UTC, slawekjaranowski commented on src/site/markdown/expected-checksums.md
> +implement, to have own ways to provide checksums to resolver. Alternatively, one may use Resolver out of the
An example implementation or demo  - how to implement will be helpful, can be on separated document.

2023-04-25 21:03 UTC, slawekjaranowski commented on src/site/markdown/expected-checksums.md
> +The Trusted Checksums provide two source implementations out of the box.
example how to configure, which property to set ... etc will be appreciated, can be as link to other document

2023-04-25 21:07 UTC, slawekjaranowski approved these changes
Generally ok, it describes used mechanizm and possibility from theoretically side. 
Examples how to use and configure will be appreciated. 
Of course on separate documents for each case as next step.

2023-04-26 07:41 UTC, cstamas commented
@slawekjaranowski re examples, all the new features (RRF, TrustedChecksums) are kinda incomplete without https://issues.apache.org/jira/browse/MRESOLVER-304 (or https://issues.apache.org/jira/browse/MNG-6303) as ultimate goal would be to commit checksums, filter config along with project sources, that is impossible today.

So I'd rather wait with examples. But still, this doco is useful, as it explains at least one confusion users hit (and reported as "bug" while it was actually OK) https://lists.apache.org/thread/nsbormhpfgqq19qzgo4rx12lg28qv0tb

2023-04-26 09:44 UTC, merged

2025-06-13 08:10 UTC, jira-importer commented
Resolve #1028

2025-06-13 08:42 UTC, jira-importer commented
Resolve #1028