[MRESOLVER-480] Document latest changes
apache/maven-resolver pull request #429
Opened 2024-02-12 14:44 UTC by cstamas

Those that may affect consumer projects.

---

https://issues.apache.org/jira/browse/MRESOLVER-480

2024-02-13 14:30 UTC, cstamas commented
@gnodet @slawekjaranowski any opinion about this?

2024-02-13 15:08 UTC, gnodet requested changes

2024-02-13 15:08 UTC, gnodet commented on src/site/markdown/upgrading-resolver.md
> +# Upgrading From 1.x to 2.x
Unwanted capitalisation

2024-02-13 15:08 UTC, gnodet commented on src/site/markdown/upgrading-resolver.md
> +## Session Handling Changes
Unwanted capitalisation

2024-02-13 15:08 UTC, gnodet commented on src/site/markdown/upgrading-resolver.md
> +Maven Resolver 2.x now delegates multiple aspects fully to consumer project, itself remaining "oblivious" about
` now fully delegates multiple aspects to the consumer project`

2024-02-13 15:08 UTC, gnodet commented on src/site/markdown/upgrading-resolver.md
> +them. This was done to lessen (or better, fully remove) any overlap of logic between Resolver, and it's major
`any overlap between the logic of the Resolver`

2024-02-13 15:08 UTC, gnodet commented on src/site/markdown/upgrading-resolver.md
> +accordingly, and if they do use any of deprecated classes from resolver (affected modules are maven-resolver-api
`if they do use any deprecated classes from the resolver`

2024-02-13 15:08 UTC, gnodet commented on src/site/markdown/upgrading-resolver.md
> +while keep full compatibility, identical to Resolver 1.x release.
`keeping`

2024-02-15 16:46 UTC, merged

2025-06-13 08:16 UTC, jira-importer commented
Resolve #1151