[MRESOLVER-502] Install/Deploy at session end
apache/maven-resolver pull request #437
Opened 2024-02-29 11:22 UTC by cstamas

With session lifecycle, resolver can now perform "install/deployAtEnd" session-wise: it merely withholds install/deploy requests and executes them at session end.

---

https://issues.apache.org/jira/browse/MRESOLVER-502

2024-02-29 11:33 UTC, michael-o requested changes

2024-02-29 11:33 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultDeployer.java
> +                logger.warn("Failure during deferred deployment:", e);
Colon is redundant

2024-02-29 11:33 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultInstaller.java
> +                logger.warn("Failure during deferred installation:", e);
same here

2024-02-29 11:41 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultDeployer.java
> +                logger.warn("Failure during deferred deployment:", e);
fixed

2024-02-29 11:51 UTC, michael-o approved these changes
No objections, let's wait for the others.

2024-02-29 15:26 UTC, gnodet reviewed
What's the benefit compared to do that in the plugin ?
I don't really see any, however, I do see a drawback which is the fact that the exception which may happen won't be caught and processed in the usual way by maven.

2024-02-29 15:44 UTC, cstamas commented
Benefits are manifold, but let me turn around the thing: I don't see any benefit in "failing the build/processing in usual way" by maven. In fact, there is only one (easily fixable) aspect where I do agree: the error output written to console. But in both case, user will have to intervene, as in case of install (usually disk full, or some permission error) or deploy (wrong URL, auth or simply network outage) in both cases user must intervene somehow (free disk space, fix perms, fix URL and/or auth, etc).

OTOH, the real benefit is that install/deploy flow already goes thru Resolver, and now that resolver became aware when session ends, I really see this as "natural fit" to place this logic. Just look at install/deploy plugins how convoluted is their logic (or Takari logic that uses LifecycleParticipant to achieve same). It just makes things natural and a LOT simpler. 

And the other huge benefit is that resolver can, if needed "rearrange" and better parallelize deploys even (not done). And last but not least, generators, that may handle some sort of "time limited session" can be invoked in rather snappy way (although current PR contains "simplistic" deferred implementation, that can be improved in this regard).

To me, this really just moves things to their "proper place".

And about error handling, IMO Maven core would need anyway some handling of errors that may happen on session or system close, as currently we have none of those in place (but baby steps).

2024-02-29 16:37 UTC, gnodet commented
> Benefits are manifold, but let me turn around the thing: I don't see any benefit in "failing the build/processing in usual way" by maven. In fact, there is only one (easily fixable) aspect where I do agree: the error output written to console. But in both case, user will have to intervene, as in case of install (usually disk full, or some permission error) or deploy (wrong URL, auth or simply network outage) in both cases user must intervene somehow (free disk space, fix perms, fix URL and/or auth, etc).
> 
> OTOH, the real benefit is that install/deploy flow already goes thru Resolver, and now that resolver became aware when session ends, I really see this as "natural fit" to place this logic. Just look at install/deploy plugins how convoluted is their logic (or Takari logic that uses LifecycleParticipant to achieve same). It just makes things natural and a LOT simpler.
> 
> And the other huge benefit is that resolver can, if needed "rearrange" and better parallelize deploys even (not done). And last but not least, generators, that may handle some sort of "time limited session" can be invoked in rather snappy way (although current PR contains "simplistic" deferred implementation, that can be improved in this regard).
> 
> To me, this really just moves things to their "proper place".

I'm not really convinced.  I don't think the logic in the resolver is very different from the one in the install/deploy plugin, and parallelisation can be done when submitting the big install/deploy request to the resolver.  Anyway, no big deal...

> And about error handling, IMO Maven core would need anyway some handling of errors that may happen on session or system close, as currently we have none of those in place (but baby steps).

Yes, this is a very important aspect imho. The error needs to properly get back to Maven, so that it can be handled correctly.  The build needs to be flagged as not successful with proper reporting, etc..., especially with `mvnd` and a remote process for example.

2024-02-29 18:33 UTC, cstamas commented
> Another question, given this is a global flag on the session, how can the install/deploy plugin set it ?

Unsure I get the question, so let me ask back: why would this be set by those plugins? Or in other words, how do you "install/deploy at end" today? By setting a user properties that IS set globally on session at Maven boot. Am really unsure why would it needed to be set by the plugin at all...

2024-02-29 18:43 UTC, cstamas commented
> I'm not really convinced. I don't think the logic in the resolver is very different from the one in the install/deploy plugin

Is a LOT different. Here, it is really plain straight forward, while in plugins it does hoops and loops to:
* figure out "is it end" (w/ respect of multi module builds, parallel builds, etc)?
* figure modules in reactor that may not use install plugin and consider them as well
* keep state and do something wildly different if "not end"
* etc.

Here, Installer/Deployer simply gets the "done done" list of artifacts that are to be installed. And done.

And plugins just "install/deploy", no logic, they are no brainer, and IMHO corresponding logic (here in this PR) is also much much simpler. 

Btw, it is a sign that "deploy at end" was not solved properly for so long...

2024-03-01 16:53 UTC, cstamas commented
While all this is nice and dandy, I agree with @gnodet 
* this PR clearly shows signs of "being tailored" for current Maven3 use case
* what consumer project should do instead, is to itself gather and create "at end" (potentially big for better parallelization) requests instead
* install/deploy is too critical to be done "at end", just before closing session

2024-03-01 16:53 UTC, closed without merging

2025-06-13 08:17 UTC, jira-importer commented
Resolve #1177