[MRESOLVER-536] Followup change: log failures
apache/maven-resolver pull request #471
Opened 2024-04-16 09:05 UTC by cstamas

Do not swallow cases like AccessDeniedEx, and log
failures. 

This PR builds upon prev PR https://github.com/apache/maven-resolver/pull/468

---

https://issues.apache.org/jira/browse/MRESOLVER-536

2024-04-16 09:23 UTC, rmannibucau approved these changes

2024-04-16 09:31 UTC, cstamas commented
ping @Jurrie

2024-04-16 11:32 UTC, michael-o requested changes

2024-04-16 11:32 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultPathProcessor.java
> +            logger.debug("Failed to set last-modified: {}", path, e);
I think this should be even on trace because it can be very verbose....

2024-04-16 11:32 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultPathProcessor.java
> +            logger.debug("Failed to set last-modified: {}", path, e);
`"Failed to set last modified date: {}"`

2024-04-16 11:52 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultPathProcessor.java
> +            logger.debug("Failed to set last-modified: {}", path, e);
fixed

2024-04-17 13:00 UTC, merged

2025-06-13 08:18 UTC, jira-importer commented
Resolve #1193