[MRESOLVER-158] Simplify SimpleDigest
apache/maven-resolver pull request #89
Opened 2021-01-12 07:38 UTC by cstamas

https://issues.apache.org/jira/browse/MRESOLVER-158

2021-01-12 07:51 UTC, michael-o requested changes

2021-01-12 07:51 UTC, michael-o commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/SimpleDigest.java
> +        this.digest = requireNonNull( md, "Not supported digests: " + Arrays.toString( HASH_ALGOS ) );
I think this should be IllegalStateException because no null has been passed, but an argument led to an inconsistent state.

2021-01-12 07:59 UTC, cstamas commented on maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/SimpleDigest.java
> +        this.digest = requireNonNull( md, "Not supported digests: " + Arrays.toString( HASH_ALGOS ) );
changed

2021-01-12 08:19 UTC, michael-o approved these changes

2021-01-12 08:28 UTC, cstamas commented
merged as 6c418e32ed9c12f1deadbf3be9ab0ab67aa09217

2021-01-12 08:28 UTC, closed without merging

2025-06-13 08:05 UTC, jira-importer commented
Resolve #880

2025-06-13 08:37 UTC, jira-importer commented
Resolve #880