[MRESOLVER-159] Mark components as Singletons
apache/maven-resolver pull request #93
Opened 2021-02-05 11:27 UTC by cstamas

When used with SISU, the components were NOT singletons
but prototypes, which is not the intent. In Guice module
they were properly marked as such.

https://issues.apache.org/jira/browse/MRESOLVER-159

PR tested with maven commit eae3074c63dbba24680d7049dc36217323c7d00b
maven ITs with maven built above 46fbd48777db99a339668b67c43bf4fce33cd824

Both passes OK

2021-02-05 15:01 UTC, michael-o requested changes
Can you consistently apply order of annotations: Singlton, Named?

2021-02-05 15:58 UTC, cstamas commented
@michael-o Not quite get your question, they are in that order (singleton, named)....

2021-02-05 20:30 UTC, michael-o commented
> @michael-o Not quite get your question, they are in that order (singleton, named)....

Apologies, I mislooked. Will test.

2021-02-06 15:11 UTC, closed without merging

2025-06-13 08:06 UTC, jira-importer commented
Resolve #922

2025-06-13 08:38 UTC, jira-importer commented
Resolve #922